### ISSUE TITLE
Find solution for compiling resources into one .bib file

### ISSUE THREAD

**Issue by bynarron** [akondrahman/59115ASE#1]
Currently, the way I have it set it is each folder has it's own .bib file; though, later, when we want to reference multiple, we will have to make a new .bib file that has all of the references in it.  It would be a better solution to have only one .bib file that all latex files reference.

**Comment by timm** [comment]
fyi-latex can include multiple bib files

\bibliography{file1,file2, file3}

so one approach is everyone writes their own bib

plan b, everyone works on https://www.mendeley.com/ (the free accounts).

**Comment by bynarron** [comment]
Thanks for the insight!
