### ISSUE TITLE
HW/Code4: Feedback from TA and Corresponding Findings 

### ISSUE THREAD

**Issue by akondrahman** [akondrahman/59115ASE#10]
The purpose of this issue to discuss what we have after implementing the suggestions from the TA, and if needed improvise. Let the discussion begin !! 
### The Suggestions

I met  Rahul, the TA on Friday and he asked us to make the following changes 
- normalized energy cannot be negative 
- neighbors should be a function of the current solution aka current x  
- make 1 million runs to get the baseline of Schaffer 
- fiddle with the number of runs
### Implementation
- to handle negative energy values  I added line # 52-54 in main.py 
- added a new function in randomGeneration.py called _getNeighborRandonmly_ it always uses the previous range to get the neighbor value  
-  changed line 26 and line 31 in energy.py. 
-  changed line # 33 in main.py 
### Findings

```
          ** baseline values are seen to be unstable for 1000 runs ** 
```
#### Config-1: number of runs to get baseline of min and max of Scaffer=1000, eMaxVal = 0.00000000001(line 20 of main.py), negative energy handled, neighbor values are **not a function of current solution**, (minRange,maxRange = -10^5, 10^5) for both baseline and neighbor solutions, counter aka number of runs =1000

![4-a](https://cloud.githubusercontent.com/assets/8557397/10120585/7302b200-6491-11e5-9490-e13fa14b0fc9.png)
#### Config-2: number of runs to get baseline of min and max of Scaffer=1000, eMaxVal = 0.00000000001(line 20 of main.py), negative energy handled, neighbor values are  **a function of current solution**, (minRange,maxRange = -10^5, 10^5) for both baseline and neighbor solutions, counter aka number of runs =1000

![4-b-1](https://cloud.githubusercontent.com/assets/8557397/10120590/8ee3d5f8-6491-11e5-92e4-f98b536886de.png)

**As shown below reached optimum at the following run !!** 

![inte_4-b-2](https://cloud.githubusercontent.com/assets/8557397/10120594/b4f0a7e4-6491-11e5-9791-8d9d38d09f6b.png)

```
                ** baseline values are seen to be stable for 1 million runs ** 
```
#### Config-3: number of runs to get baseline of min and max of Scaffer=1000000, eMaxVal = 0.00000000001(line 20 of main.py), negative energy handled, neighbor values are  **a function of current solution**, (minRange,maxRange = -10^5, 10^5) for both baseline and neighbor solutions, counter aka number of runs =1000

![4-c-3](https://cloud.githubusercontent.com/assets/8557397/10120596/c9d7917c-6491-11e5-8271-999cb98c8012.png)
#### Config-4: number of runs to get baseline of min and max of Scaffer=1000000, eMaxVal = 0.00000000001(line 20 of main.py), negative energy handled, neighbor values are  **a function of current solution**, (minRange,maxRange = -10^5, 10^5) for both baseline and neighbor solutions, counter aka number of runs =100000

```
                  ** there a lot of drunk solutions at the beginning** 
```

![4-d-a](https://cloud.githubusercontent.com/assets/8557397/10120606/2ef8ac94-6492-11e5-90f3-7ae203afdec8.png)

```
                  ** sobers at the end ** 
```

![4-d-b](https://cloud.githubusercontent.com/assets/8557397/10120607/3269f1ee-6492-11e5-9132-48c2444b0d49.png)
#### Config-5: number of runs to get baseline of min and max of Scaffer=1000000, eMaxVal = 0.00000000001(line 20 of main.py), negative energy handled, neighbor values are  **a function of current solution**, (minRange,maxRange = -10^5, 10^5) for both baseline and neighbor solutions, counter aka number of runs =10000

```
                  ** there a lot of drunk solutions at the beginning** 
```

![4-e-1](https://cloud.githubusercontent.com/assets/8557397/10120610/416d1482-6492-11e5-9681-e38735a9a53e.png)
                      *\* sobers at the end *\* 
![4-e-2](https://cloud.githubusercontent.com/assets/8557397/10120611/4d456610-6492-11e5-8800-6143cf6a9cce.png)

**Comment by akondrahman** [comment]
FYI. 
The code that I have committed for hw/code/4 (https://github.com/akondrahman/59115ASE/tree/master/hw/code/4) is for _Config-4_. Feel free to make changes to see different output combinations.

**Comment by bynarron** [comment]
Hey all,

I'll see what I can get around to this week.  I have an exam, the
engineering career fair, meetings on research and independent study
progress, and a networks assignment all to be finalized by Thursday
evening.  Needless to say, I'm slammed this week.

Maybe Friday evening I'll have some free time to do another lit review and
with on some code.

Bennett

**Comment by manish211** [comment]
@akondrahman  I will check it out.

**Comment by akondrahman** [comment]
hw/code/4 is graded and I am closing this issue.

**Comment by manish211** [comment]
I need to talk to you about this in our next meeting
