### ISSUE TITLE
Probable Software Models to Implement 

### ISSUE THREAD

**Issue by akondrahman** [akondrahman/59115ASE#11]
Folks, 
I have listed a few models of different sizes and types that I got from the book (and looked interesting to me). Let's all take a look at them and determine which one will be a good fit for the MASE project (taking Dr. Menzies' approval). 
1.  Brook's Law Model (page # 17 )
2.  Exhaustion Model (page # 224 )
3.  Learning Curve Model (page # 231 ) 
4.  Hiring Delay Model (page # 256 )
5.  Global Process Feedback Model (page # 293 )
6.  Top Level Reuse Model (page # 300 ) 
7.  COTS glue development model (page # 314 )
8.  Integrated project model defect flow chain (page # 329 )
9.  Causal Model (page # 340 )
10. Project Contention Model (page # 415 )
11. Earned Value Model (page # 452 )

**Comment by manish211** [comment]
Great! Let's discuss this in our  next meeting.

**Comment by bynarron** [comment]
@timm we are considering selecting a model to implement for the project from the book by Madachy.  The following models are ones that we have determined might fit within the range of difficulty and feasibility that we are looking for.  Any feedback would be greatly appreciated.

Favored Models (Ranked):

(1) 8 -- Integrated project model defect flow chain (page # 329 )
(2) 10 -- Project Contention Model (page # 415 )
(3) 11 -- Earned Value Model (page # 452 )

**Comment by timm** [comment]
this is a great list

can you please post it to the class list?

t

> Brook's Law Model (page # 17 )
> Exhaustion Model (page # 224 )
> Learning Curve Model (page # 231 )
> Hiring Delay Model (page # 256 )
> Global Process Feedback Model (page # 293 )
> Top Level Reuse Model (page # 300 )
> COTS glue development model (page # 314 )
> Integrated project model defect flow chain (page # 329 )
> Causal Model (page # 340 )
> Project Contention Model (page # 415 )
> Earned Value Model (page # 452 )

**Comment by akondrahman** [comment]
Posted   ... any recommendations for our team, Dr. @timm?

**Comment by timm** [comment]
Bigger the better
