### ISSUE TITLE
Version History of Projects 

### ISSUE THREAD

**Issue by akondrahman** [akondrahman/59115ASE#12]
In our preliminary discussion with Dr. Menzies, he asked us to find some background information from the PROMISE repository that can be used as input to our model of interest. The following presents the list of projects that have multiple versions and is available at http://openscience.us/repo/defect/ck/. Here goes the list of projects and their version history: 
#### Ant:

1.3: March 03, 2001 
1.4: Sep 03, 2001 
1.5: July 10, 2002 
1.6 Dec 18, 2003 (Version 1.6.0 to be exact)
1.7 Dec 19, 2006 (Version 1.7.0 to be exact)
RefF: https://ant.apache.org/faq.html
#### Camel:

1.0: 02/Jul/07 (Version 1.0.0)
1.2: 19/Oct/07 (Version 1.2.0)
1.4: 22/Jul/08   (Version 1.4.0)
1.6: 16/Feb/09 (Version 1.6.0)
Reff: https://issues.apache.org/jira/browse/CAMEL?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel&subset=-1 
#### Forrest:

0.6: 14/Sep/08 
0.7: 02/May/13 
0.8: 18/Apr/07 
Reff: https://issues.apache.org/jira/browse/FOR/?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel   
#### Ivy:

1.1: 2005-06-13 Reff: http://ant.apache.org/ivy/history/1.1.html
1.4: 2006-10-09 Reff:http://ant.apache.org/ivy/history/1.4.html
2.0: Jan 20, 2009 Reff:http://ant.apache.org/ivy/ 
#### Jedit:

3.2: ? 
4.0: ?
4.1: ?
4.2: ?
4.3: December 23 2009 Reff: http://jedit.org/index.php?page=devel
#### Log4j:

1.0:  ?
1.1:  ?
1.2: 2012-05-13 Reff:https://logging.apache.org/log4j/1.2/ 
#### Lucene:

2.0: 26/May/06 Reff:https://issues.apache.org/jira/browse/LUCENE/fixforversion/12310853/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel 
2.2: 19/Jun/07 Reff:https://issues.apache.org/jira/browse/LUCENE/fixforversion/12312328/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel 
2.4: 08/Oct/08 Reff: https://issues.apache.org/jira/browse/LUCENE/fixforversion/12312681/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel
#### PBeans:

1: ?
2: ? 
#### POI:

1.5: Version 1.5 (2002-05-06) 
2.0: Version 2.0-FINAL (2004-01-26) 
2.5: Version 2.5-FINAL (2004-02-29)
3.0: Version 3.0-FINAL (2007-05-18)
Reff: https://poi.apache.org/changes.html 
#### Prop:

1: ? 
2: ?
3: ?
4: ?
5: ?
6: ?
#### Synapse:

1.0: ?
1.1: 12/Nov/07 
Reff: https://issues.apache.org/jira/browse/SYNAPSE/fixforversion/12312845/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel
1.2: 23/Dec/07 
Reff: https://issues.apache.org/jira/browse/SYNAPSE-212?jql=project%20%3D%20SYNAPSE%20AND%20fixVersion%20%3D%201.2%20ORDER%20BY%20updated%20DESC%2C%20priority%20DESC%2C%20created%20ASC
#### Velocity:

1.4: ?
1.5: 2007-01-28
1.6: 2008-12-01
Reff: http://velocity.apache.org/engine/devel/changes-report.html 
#### Xalan:

2.4: 03/Oct/02
2.5: 14/Apr/03
2.6: 29/Feb/04 
2.7: 08/Aug/05
Reff: https://issues.apache.org/jira/browse/XALANJ/?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel
#### Xerces:

1.2: ?
1.3: ?
1.4: ?

_?_ means I did not find the version history

**Comment by manish211** [comment]
@akondrahman  Can we use this information in any way for our project model?
