### ISSUE TITLE
12 more papers for the Final Paper

### ISSUE THREAD

**Issue by bynarron** [akondrahman/59115ASE#13]
Hey all,

We need to discover 12 more papers to include in our final paper.  Just creating an issue to serve as a repository for candidate papers.

**Comment by manish211** [comment]
12 more papers? Are you talking about project?

**Comment by bynarron** [comment]
The final paper should include 20 papers.  We don't have to analyze then
line we did the first 8... But they need to be cited in our final paper.

**Comment by manish211** [comment]
okay

**Comment by akondrahman** [comment]
I think we still need to briefly describe the _new 12 _ papers in the _big report_. I hereby propose to divide the 12 papers into groups of four, i.e. four papers for each person. I have targeted the following five: 
- Predicting failures with developer networks and social network analysis by _Meenley et al. (FSE 2008)_
- Mining metrics to predict component failures by _Naggapan et al. (ICSE 2006)_
- Studying  the  impact  of  social structures on software quality by _Bettenburg et al. (ICPC 2010)_ 
- Studying the impact of dependency network measures on software quality by _Nguyen et el. (ICSM, 2010)_
- Cross-project defect prediction: a large scale experiment on data vs. domain  vs.  process by _Zimmerman et al. (FSE, 2009)_

The first two are taken from the paper tiled _Ecological inference in empirical software engineering (hw/read/1)_. The last three are taken from the paper titled _ Think Locally, Act Globally: Improving Defect and Effort Prediction Models (hw/read/7)_

**Comment by bynarron** [comment]
We have 7 papers left before we can begin writing the paper.
