### ISSUE TITLE
Approach for running DE algorithm on the Madacky model

### ISSUE THREAD

**Issue by manish211** [akondrahman/59115ASE#16]
Dear Dr. @timm ,
                        Could you please verify our approach for applying the DE algorithm on our model?

Lets consider the Madacky model as a blackbox.

**`GenerateCandidates()`**

```
* We generate the input auxiliary vector as [A1,A2,….A17] ( decision vector)
* We pass the decision vector to the Black Box
* Black Box runs for 30 minutes ( say t=30 minutes)
* After 30 minutes, Black Box returns f1, f2
* We update the score of candidate as = f1 + f2


```

**Call `GenerateCandidate()` 170 times ( np = 17*10)**

Run the DE on the frontier containing 170 candidates for 17 decisions and 2 objectives

**DE End Result** : Best value of f1+f2, f1, f2 , and the corresponding decision vector [A1",A2",…..A17"] for the given time t=30 minutes and given constraints

**Comment by manish211** [comment]
Tagging @bynarron @akondrahman

**Comment by timm** [comment]
runs for 30 minutes? why? which madachy model is this?

t

**Comment by manish211** [comment]
that is just for illustration. I am talking about the time parameter - t here.

**Comment by manish211** [comment]
We are doing this model from the book

(1) 8 -- Integrated project model defect flow chain (page # 329 )

**Comment by akondrahman** [comment]
_run for 30 minutes_ is a vague/confusing term ... we can say it _n_, where _n_ is the number of times the model is going to run. _n_ can be of any time unit.  

To clarify more, here _n_ is equivalent to _tmax_ in the Diapers model (https://github.com/txt/mase/blob/master/src/dsl101.md)

**Comment by timm** [comment]
what not say, time to create, say, 100 bugs then report bugs/time as the performance metric?
