### ISSUE TITLE
Baseline for 'Integrated Defect Model' 

### ISSUE THREAD

**Issue by akondrahman** [akondrahman/59115ASE#17]
##### Approach
- assume 11 auxiliaries to be between 0 & 1 
- assume erst of the four auxiliaries to follow a certain equation as mentioned in #15  
- run model 1000, 10000, 100000, 1000000 times 
#### Output
- minimum of _Undetected Active Errors_ = 0  for different runs 
- maximum of _Undetected Active Errors_  = increases with the increase of time ~3000 for 1000 runs, 
  ~30,000 for 10, 000 runs etc. 
- minimum of _Undetected Passive Errors_   = ~ -30 across different runs 
- maximum of _Undetected Passive Errors_   = ~ 0 across different runs

**Comment by manish211** [comment]
@akondrahman  Who is supposed to look or review this?
Can you assign this to someone?

**Comment by manish211** [comment]
okay. Looks like we need Dr. Tim's review here.

**Comment by manish211** [comment]
Completed
