### ISSUE TITLE
Research Questions and Hypothesis to be verified/reviewed

### ISSUE THREAD

**Issue by manish211** [akondrahman/59115ASE#2]
The paper does not explicitly mention research questions like RQ1,RQ2. Hence the research questions need to be verified/reviewed by the teammates. Same for hypothesis.

**Comment by timm** [comment]
why not list what you think are the RQs in this comment and let the team debate them here?

**Comment by bynarron** [comment]
I put that in there for elaboration to keep our notes as congruent as
possible from poster to poster.  You won't always find research questions,
goals, or hypotheses started in a paper, especially if there is no
experiment being conducted.  There are typically implied version of them
though.

**Comment by bynarron** [comment]
*Paper to paper

**Comment by manish211** [comment]
Here are the questions that I put in our notes.

While pursuing this goal,this paper tries to answer the following research questions:
1. What is the right level of aggregation to study?
2. How does the level of study affect the truth, meaning and relevance of the findings?
3. Are prediction models subject to ecological inference risk?
4. Is hypothesis testing subject to ecological inference risk?
5. What are the effects of aggregation on model quality?
6. Do inferences drawn from models built at aggregated levels transfer to disaggregated levels used to build the aggregations?

Below are the two hypothesis:
- “Prediction models are subject to ecological inference risk” 
- “Hypothesis testing is subject to ecological risk”

**Comment by bynarron** [comment]
Sounds both applicable and intelligible.  I would say, from only having
read the abstract yet, it sounds appropriate.

**Comment by manish211** [comment]
Let's keep this open until we have read the entire paper! I read the first four pages thoroughly, skimmed through the methodology, findings and conclusion. The questions are relevant but we might want to reduce the number of questions.

**Comment by akondrahman** [comment]
These are my views, but I might be wrong:
1. What is the right level of aggregation to study?
   I agree 
2. How does the level of study affect the truth, meaning and relevance of the findings?
   Partially agree. To be more accurate, I would say 'which factors associated with aggregated and dis-aggregated level of software affect empirical results '  
3. Are prediction models subject to ecological inference risk?
   I disagree. I would say 'are empirical findings that propose and test software models, subject to ecological inference risk ?' 
4. Is hypothesis testing subject to ecological inference risk?
   I disagree. I don't think the paper does that at all. 
5. What are the effects of aggregation on model quality? 
   Falls under point # 3 
6. Do inferences drawn from models built at aggregated levels transfer to disaggregated levels used to build the aggregations?
   I disagree. I don't think the paper does that at all.

**Comment by timm** [comment]
profound questions. you (and/or your group) free thurs 3pm to talk about this?

p.s. not for your class work but just so you know it, i got into ecological and local/global in http://menzies.us/pdf/12gense.pdf

**Comment by akondrahman** [comment]
Professor @timm, 
I have a class at 3PM on main campus on Thursday. Can we meet some other time at your convenience ?

**Comment by manish211** [comment]
@akondrahman Thanks for the review. Here's some pointers.
- For point 2, the stated question is on a broad level . Yes, the author does go into specific factors that are associated with the risk of ecological fallacy
- For point 3 - You should not disagree :P . The author says "These findings support the following claims". See page no - 6, "Experimental Methods" section.
- For point 4 - Same as above. See the "Experimental Methods" section
- For point 6 - See page no - 9, just above the "Threats To Validity" section

**Comment by akondrahman** [comment]
@manish211  I re-read it, I agree with you point # 6. 

But, I don't think the authors answered # 4. Even though they say _Is hypothesis testing subject to ecological inference risk?_, they are not looking at hypotheses testing; they are looking at _inferences that are drawn from different levels of analysis_. Hypothesis testing is just a tool to do that. I would argue the wording is confusing, at the very least. 

I also think _Are prediction models subject to ecological inference risk?_ is a wide claim; there are many prediction models (defect, performance, popularity etc.) specific to a certain application (security in open source software, Github repos, HCI in Software Engg. ); I don't thin we cannot generalize this paper's findings and apply it everywhere. That is still an **open research area** 

Thanks for the feedback. Interesting discussion !

**Comment by timm** [comment]
> ; I don't thin we cannot generalize this paper's findings and apply it everywhere. That is still an open research area

fyi: i think we can. i did. i do. see http://menzies.us/pdf/12gense.pdf

**Comment by timm** [comment]
> Professor @timm, 
> I have a class at 3PM on main campus on Thursday. Can we meet some other time at your convenience ?

not this week. icse deadline is friday and there are grants to write and new phd students to process and and and. 

maybe we need to grab coffee after class on tuesday? i hate our campus... nowhere we can really go that is not a hike.

**Comment by akondrahman** [comment]
Professor @timm, 
I am fine with coffee after today's class.

**Comment by timm** [comment]
Anyone else in your group can come? I'll get a grad student to truck in coffee and we'll sit on the foyer outside the lecture.

**Comment by manish211** [comment]
Dr. Tim, 
              I will join too !

**Comment by bynarron** [comment]
Dr. Menzies,

I also am able to join after class.

Thanks!
Bennett

**Comment by timm** [comment]
ok. coffee and doughnuts organized.

**Comment by akondrahman** [comment]
Thanks Professor !

**Comment by bynarron** [comment]
I was on the fence.... now I think I'm in. har
