### ISSUE TITLE
Paper for Big Project

### ISSUE THREAD

**Issue by bynarron** [akondrahman/59115ASE#21]
We need to compose our paper for our large project, which, according to Dr. Menzies, should be thorough enough to express our understanding of our model, optimization and procedures.

**Comment by akondrahman** [comment]
Related work for project paper: 
1. Software Process Dynamics, Raymond Madachy  
2. Software Project Dynamics: An Integrated Approach, Abdel-Hamid, and Madnick 
3. Differential Evolution – A Simple and Efficient Heuristic for global Optimization over Continuous Spaces (Original Paper) by Storn and Price
4. Two hybrid differential evolution algorithms for engineering design optimization (Application of DE in engineering design) Liao
5.  Multi-objective differential evolution for scheduling in grid applications (Application of DE in Grid Computing) Talukder et al.
6. Differential Evolution as Applied to Electromagnetics  (Application of DE in electro magnetics ) Rocca et al. 
7. An Evaluation of Differential Evolution in Software Test Data Generation (Differential Evolution for SWE test Data Generation) by Becerra et al. 
8. DE for SWE Testing Effort - Nasar et al.  
9. Predicting failures with developer networks and social network analysis by Meenley et al. (FSE 2008)
10. Mining metrics to predict component failures by Naggapan et al. (ICSE 2006)

**Comment by akondrahman** [comment]
We now have a 3100 word report ... I am adding the other materials recommended by Dr. Menzies incrementally.

**Comment by bynarron** [comment]
Sounds good!
