### ISSUE TITLE
Review of project report 

### ISSUE THREAD

**Issue by manish211** [akondrahman/59115ASE#27]
Creating this issue to review the project report. 

To be reviewed by Manish and Bennett and submit the analysis/feedback by commenting in this issue.

For any changes that does not have any dependency on Akdond, Manish and Bennett will directly make changes in the report and discuss the same by commenting on this issue.

Assigning to Bennett as of now. Once Bennett does the review, he will assign to Manish

**Comment by bynarron** [comment]
I'll review this tomorrow.

I'm also not sure that I'll have the lit review thing done by tomorrow, but
that shouldn't be a huge issue since it isn't due until the 15th.  I'll get
as much finished as I can before tomorrow evening, and then resume after my
CSC 570 final.

**Comment by manish211** [comment]
@bynarron  okay. I didnt know that its due on 15th. alright np

**Comment by bynarron** [comment]
The project report is due Tuesday... the Literature review is due on the
15th.

**Comment by manish211** [comment]
ooh...I misread the "lit" part. Alright. I will do the review soon today

**Comment by bynarron** [comment]
You're fine, Manish. I'm saying don't stress about the literature reviews
that you're doing, our big paper isn't due until the 15th.

The paper that Akond wrote is due on Tuesday.

We have plenty of time to look over the Big Literature Review/Survey
paper.  I hope to have most of it written by the end of the day today.

**Comment by manish211** [comment]
alright. Thanks.
