### ISSUE TITLE
Readings - Divide and Conquer?

### ISSUE THREAD

**Issue by bynarron** [akondrahman/59115ASE#3]
I have a suggestion about how we might best use our time and resources to cover a lot of ground on the reading.  We could first agree on a set of papers to read for our review.  Then, each week or predetermined time period, we could each read one and write the review.  We could schedule a meeting time once a week (e.g., Thursday after class) to spend about 45min-1hr presenting our papers to each other.

This would supply us with a deadline to motivate our reading, and also afford us some extra time to attack some of the coding projects.  Ideas?

**Comment by manish211** [comment]
Yup. Sounds like a plan ! I am in.
