### ISSUE TITLE
Project Idea!

### ISSUE THREAD

**Issue by bynarron** [akondrahman/59115ASE#4]
Last semester I performed a literature review on applications of "resilience" (i.e., the ability for a system to return to a good state following successive disturbances) across disciplines--including socio-ecology, ecology, computer science, economics, etc--for an independent study with Dr. Munindar Singh.

This semester, I am doing another independent study in which I will be working with Dr. Jon Doyle to define the domain of system resilience, logically.  This work will elucidate the variables that we believe are important in understanding what defines and promotes resilience in a system

To test and fine tune these variables, we could incorporate the cumulative results from these independent studies to attempt to model resilience via MASE.  We could use the techniques we learn in Dr. Menzies course (and with his approval) to programmatically derive an algorithm that converges on maximizing resilience in a system.

This is, indeed, a hard problem; but, could result in a publishable paper.  I intend to seek publication for the work in both independent studies; however, the data modeling that would be provided by our work in Dr. Menzies' class would make it more robust.  So, Manish and Akond, if you're interested, I would like to pursue this paper together.

If we agree that this is a viable idea, I will talk to Dr. Menzies when I return from Spain to discuss the feasibility of this proposed project.

Ideas?

**Comment by manish211** [comment]
@bynarron  I think we should have a meeting together about this where we go further into the details. After that, we should discuss the same with Dr. Tim as he would be the best person to decide the viability of the project and whether it can be completed within the time-frame we have. He will be in a better position to foresee all the challenges that we could possibly encounter.

**Comment by bynarron** [comment]
Agreed.

**Comment by akondrahman** [comment]
Great idea ! Thanks for considering. 
Count me in, please. 
I also agree with Manish; before even brainstorming we should talk with Dr. Menzies and see what he says.

**Comment by bynarron** [comment]
Definitely. I would want to make sure that completing the project would be
feasible.

**Comment by timm** [comment]
dr @timm wants exceptional and motivated students to succeed brilliantly with a project small enough to complete in one term, and large enough to stress and stretch them.

now the models @bynarron are discussing are consuming the time of a very large and very skilled team

so i ask.... what is some domain constraint that can make you work on an interesting subset of of the whole thing?
