### ISSUE TITLE
Reading Task : Selected Papers for 'Backward & Forward Mode'

### ISSUE THREAD

**Issue by akondrahman** [akondrahman/59115ASE#6]
Folks, 
I have come up with a list of papers for 'Backward Mode' and 'Forward Mode'. 
Papers in the 'Backward Mode' are highly cited papers published from 2008-2010 and are cited by primary paper of interest. If this list looks good to everyone, we can go ahead and start reading the papers.
_Note-1:_ I have excluded papers where Dr. Menzies is an author 
_Note-2:_ The citation counts are obtained from Google Scholar  
### Backward Mode
- Benchmarking Classification Models for Software Defect Prediction: A Proposed Framework and Novel Findings, _396 citations_
- The influence of organizational structure on software quality: an empirical case study _234 citations_
- Does distributed development affect software quality?: an empirical case study of Windows Vista, \* 168 citations*
- A systematic and comprehensive investigation of methods to build and evaluate fault prediction models. _148 citations_
### Forward Mode
- Think locally, act globally: improving defect and effort prediction models, _41 citations_
- Recalling the "imprecision" of cross-project defect prediction, _36 citations_
- How, and why, process metrics are better, _30 citations_

**Comment by akondrahman** [comment]
I will take the following for now: 
- Think locally, act globally: improving defect and effort prediction models
- The influence of organizational structure on software quality: an empirical case study

**Comment by manish211** [comment]
:+1: 
I think we are supposed to go backwards first . :thought_balloon: I am taking the below: 
- The influence of organizational structure on software quality: an empirical case study 234 citations
- Does distributed development affect software quality?: an empirical case study of Windows Vista, \* 168 citations*

:v:

**Comment by bynarron** [comment]
I will read and summarize the following:
- BACKWARDS:
  - "A systematic and comprehensive investigation of methods to build and evaluate fault prediction models. 148 citations"
- FORWARDS:
  - "How, and why, process metrics are better, 30 citations"

**Comment by bynarron** [comment]
@akondrahman Do these papers have "historical context" for the first paper we read?

**Comment by akondrahman** [comment]
The _backwards papers_ are all cited by the _Ecological Inference_ paper. I skimmed them briefly and I  think they all do.

**Comment by bynarron** [comment]
Awesome! I just watched the video on the read0123456789 post.  Wanted to
make sure.  Thanks!

**Comment by manish211** [comment]
It seems that nobody has done the below one:
**Benchmarking Classification Models for Software Defect Prediction: A Proposed Framework and Novel Findings, 396 citations**

**Comment by manish211** [comment]
I have completed Does distributed development affect software quality?: an empirical case study of Windows Vista. Will do Benchmarking next

**Comment by manish211** [comment]
Okay. I have completed Benchmarking paper . It is in read/5 folder. Distributed Development is in read/3 folder. :persevere:
