### ISSUE TITLE
Simulated Annealing : Acceptance Probability Function to be verfied : Code 4

### ISSUE THREAD

**Issue by manish211** [akondrahman/59115ASE#7]
Manish to verify the acceptance probability function. The notes indicate new - old whereas other sites on Internet say " old - new". To verify the same. Attaching screenshot. old-new works . But how do you make it run 1000 times? Right now either we run the model multiple times or set the energy max to be negative. Attaching screenshot.
![screen shot 2015-09-05 at 12 38 43 am](https://cloud.githubusercontent.com/assets/11049791/9697714/01c2bdc8-5367-11e5-9a6a-780a21bf784f.png)

**Comment by bynarron** [comment]
I am back from Spain. Are there any plans to meet to work on code this week?  You guys are killing it, and I want to catch up.

**Comment by manish211** [comment]
No. We have not killed it yet completely :neckbeard:

**Comment by bynarron** [comment]
Haha!  I mean as far as your collective vigor with regard to the
assignments in general.  I began the semester having to cover my bases for
travel... Now I'm able to fully commit (no pun intended)

**Comment by akondrahman** [comment]
It only took 2-3 hours to write up the code ... but there is this one subtle thing with _heating and cooling_ and that is why we are not getting expected results ... @bynarron , feel free to look at the code and send your thoughts

**Comment by manish211** [comment]
The problem is as I mentioned above 
- We need to verify the equation - whether it should be "old - new" or "new -old"
- Whether the acceptance probability should <= random probability 

My views:
- old -new with acceptance probability <= random probability gives good results. I mean the number of ? reduces  ( number of times not good enough solutions are accepted)

**Comment by manish211** [comment]
Looks like I got it working! ha ha :neckbeard:

@akondrahman  Check the attachment. The number of ? is decreasing as we reduce the temperature. 

@timm  Professor - Could you please validate if this output looks correct? We started with high temperature ( denoted by **`counter/Kmax = 1`**and we reduce the counter value which is same as reducing the temperature). However, I think there is a mistake in the notes mentioned in github course page. It says **probability of acceptance** is computed using **`delta = -(current energy - neighbour energy).`  I think it should be  `-(neighbour energy - current energy).`** . I am considering the problem to be a minimization problem here (Convex).

<img width="1280" alt="uploadme" src="https://cloud.githubusercontent.com/assets/11049791/9727474/503f6ac4-55cd-11e5-8f9f-4edc197c404b.png">

**Comment by timm** [comment]
This all looks right
- small quibble: wished you'd reduced font before snipping... the wrap makes it a little hard to read

Note the features of the above:
- Each row is 50 evals. 20 rows = 1000 repeats
- Count  the number of dubious decisions (marked with "?") on each row 
  - note that this count decreases (very few on last rows, very many on final row)
- Count the number of better decsions (marked with "!") on each row
  - note they get rarer and rarer
  - in fact, none after about 500 evals

so this is as expected. in later homeworks we will
- implementing early stopping (if no improvement in N eras, stop (where, say, 50 evals = 1 era))
- implement returning the era-when-we-stopped as the results of the inference
- implement the statistical comparison of  era results from different optimizers

**Comment by manish211** [comment]
@timm  Professor I will take care about the font going ahead. Thank you for your valuable feedback.

**Comment by timm** [comment]
of make the eras 40 long instead of 50

or kill the space between each char (is there a space between each char?)

**Comment by manish211** [comment]
We did not have space in between. So I made the eras 40 long instead of 50.
<img width="982" alt="newpic" src="https://cloud.githubusercontent.com/assets/11049791/9770956/f7c5c066-5700-11e5-98f2-2f5127d9d634.png">

**Comment by timm** [comment]
ok

totally optional but i'd make the "score car" same line as the output and i'd vertically align the scores with a little pad space.

on the other hand, sometimes life is too short  for that level of pedantry
